version: '3.8'

services:
  web:
    build: .
    container_name: fastapi-server
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo_data:/data/db
    restart: always

networks:
  backend:

volumes:
  mongo_data:
